# Generated by Django 3.2.25 on 2025-06-17 19:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Juegos_Indie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('Nombre_del_juego_indie', models.TextField()),
                ('Fecha_de_salida', models.DateTimeField(blank=True, null=True)),
                ('Descripcion', models.TextField()),
                ('Precio', models.TextField()),
                ('Plataformas_disponibles', models.TextField()),
                ('Fecha_de_la_ultima_actualizacion', models.TextField()),
                ('fecha_publicacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('hora_creacion', models.DateTimeField(blank=True, null=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
