# Generated by Django 3.2.25 on 2025-06-19 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juegos_indie',
            name='Fecha_de_la_ultima_actualizacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
