# Generated by Django 3.2.25 on 2025-06-26 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_juegos_indie_fecha_de_la_ultima_actualizacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='juegos_indie',
            name='Imagen',
            field=models.ImageField(null=True, upload_to='Img_Juegos_Indie/'),
        ),
    ]
