# Generated by Django 3.2.25 on 2025-06-26 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_juegos_indie_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='juegos_indie',
            name='Imagen',
        ),
        migrations.AlterField(
            model_name='juegos_indie',
            name='Fecha_de_la_ultima_actualizacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='juegos_indie',
            name='Fecha_de_salida',
            field=models.DateField(blank=True, null=True),
        ),
    ]
